CREATE TABLE IF NOT EXISTS `cp_pwall_log`(
	`id` INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`account_id` INT(11) UNSIGNED NOT NULL,
	`order` CHAR(255) DEFAULT '',
	`amount` INT(11) NOT NULL,
	`credits` INT(11) NOT NULL,
	`type` INT(4) DEFAULT 0,
	`date` DATETIME DEFAULT '0000-00-00 00:00:00'
);